# This is manifest file for the Swift Package Index for it to auto-generate and
# host DocC documentation.
#
# For reference see https://swiftpackageindex.com/swiftpackageindex/spimanifest/documentation/spimanifest/commonusecases#Host-DocC-documentation-in-the-Swift-Package-Index

version: 1
builder:
    configs:
    - documentation_targets: [Gravatar, GravatarUI]
      platform: ios
      custom_documentation_parameters: [--include-extended-types]
