swiftlint_version: 0.57.1
only_rules: # Rules to run
  - contains_over_filter_is_empty
  - empty_count
  - empty_string
  - custom_rules

# If true, SwiftLint will treat all warnings as errors.
strict: true

included:
  - Sources
  - Tests

custom_rules:
  no_ns_localized_string:
    included:
      - "Sources/.*\\.swift"
    name: "No NSLocalizedString"
    regex: "NSLocalizedString\\("
    match_kinds:
      - identifier
    message: "Use `SDKLocalizedString()` instead of `NSLocalizedString()`."
    severity: error
