# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Variables used in this pipeline are defined in `shared-pipeline-vars`, which is `source`'d before calling `buidkite-agent pipeline upload`

agents:
  queue: "mac"
env:
  IMAGE_ID: $IMAGE_ID

steps:
  #################
  # Lint Source files
  #################
  - label: "🧪 Lint"
    key: "lint"
    command: |
      echo "--- 🛠 Linting"
      make lint

  #################
  # Build and Test
  #################
  - label: "🧪 Build and Test"
    key: "test"
    command: |
      validate_swift_package
    plugins: [$CI_TOOLKIT]
  
  #################
  # Build Demo
  #################
  - label: "🧪 Build Demo Project"
    key: "test_demo"
    command: |
      .buildkite/commands/build-demos.sh
    plugins: [$CI_TOOLKIT]

  ###################
  # Validate Gravatar Podspec
  ###################
  - label: "🧪 Validate Gravatar Podspec"
    key: "validate_gravatar"
    command: |
      .buildkite/commands/validate-pods.sh "Gravatar.podspec"
    plugins: [$CI_TOOLKIT]

  #######################
  # Publish the Gravatar Podspecs (if we're building a tag)
  #######################
  - label: "⬆️ Publish Gravatar Podspecs"
    key: "publish_gravatar"
    command: |
      .buildkite/commands/publish-pod.sh "Gravatar.podspec"
    plugins: [$CI_TOOLKIT]
    depends_on:
      - "test"
      - "test_demo"
      - "validate"
      - "lint"
    if: build.tag != null
    agents:
      queue: "mac"

  ###################
  # Validate Gravatar UI Podspec
  ###################
  - label: "🧪 Validate Gravatar UI Podspec"
    key: "validate_gravatarui"
    command: |
      .buildkite/commands/validate-pods.sh "GravatarUI.podspec"
    plugins: [$CI_TOOLKIT]


  #######################
  # Publish Gravatar UI Podspec (if we're building a tag)
  #######################
  - label: "⬆️ Publish Gravatar UI Podspecs"
    key: "publish_gravatar_ui"
    command: |
      .buildkite/commands/publish-pod.sh "GravatarUI.podspec"
    plugins: [$CI_TOOLKIT]
    depends_on:
      - "test"
      - "test_demo"
      - "validate"
      - "lint"
    if: build.tag != null
    agents:
      queue: "mac"
