# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Variables used in this pipeline are defined in `shared-pipeline-vars`, which is `source`'d before calling `buidkite-agent pipeline upload`

agents:
  queue: "mac"
env:
  IMAGE_ID: $CURRENT_IMAGE_ID

steps:
  #################
  # Lint Source files
  #################
  - label: "🕵️ Lint"
    key: "lint"
    command: |
      echo "--- 🛠 Linting"
      make lint

  #################
  # Build and Test
  #################
  - group: "📦 Build and Test Swift Package"
    steps:
      - label: "📦 Build and Test Swift Package (Swift {{matrix.swift_version}})"
        key: "test"
        command: |
          validate_swift_package test device_model:"{{matrix.device_model}}" os:"{{matrix.device_os}}"
        plugins: [$CI_TOOLKIT]
        env:
          IMAGE_ID: "{{matrix.image_id}}"
        matrix:
          setup: # Specify the current version of Xcode, Swift, a device, and the required version of iOS
            image_id: $CURRENT_IMAGE_ID
            swift_version: $CURRENT_SWIFT_VERSION
            device_model: $CURRENT_DEVICE
            device_os: $CURRENT_OS
          adjustments: # Specify additional versions of Xcode, Swift, a device, and the required version of iOS
            - with:  # Swift 5.9
                image_id: $SWIFT_5_9_IMAGE_ID
                swift_version: $SWIFT_5_9_VERSION
                device_model: $SWIFT_5_9_DEVICE
                device_os: $SWIFT_5_9_OS
            - with:  # Swift 6.0
                image_id: $SWIFT_6_0_IMAGE_ID
                swift_version: $SWIFT_6_0_VERSION
                device_model: $SWIFT_6_0_DEVICE
                device_os: $SWIFT_6_0_OS

  ###################
  # Validate Podspec
  ###################
  - group: "🔬 Validate Podspecs"
    steps:
      - label: "🔬 Validate Podspecs (Swift {{matrix.swift_version}})"
        key: "validate"
        command: |
          .buildkite/commands/validate-pods.sh
        plugins: [$CI_TOOLKIT]
        env:
          IMAGE_ID: "{{matrix.image_id}}"
        matrix:
          setup: # Specify the current version of Xcode and Swift
            image_id: $CURRENT_IMAGE_ID
            swift_version: $CURRENT_SWIFT_VERSION
          adjustments: # Specify additional versions of Xcode and Swift
            - with:
                image_id: $SWIFT_5_9_IMAGE_ID
                swift_version: $SWIFT_5_9_VERSION
            - with:
                image_id: $SWIFT_6_0_IMAGE_ID
                swift_version: $SWIFT_6_0_VERSION

  #######################
  # Publish the Podspecs (if we're building a tag)
  #######################
  - label: "⬆️ Publish Podspecs"
    key: "publish"
    command: |
      .buildkite/commands/publish-pod.sh "Gravatar.podspec"
      .buildkite/commands/publish-pod.sh "GravatarUI.podspec"
    plugins: [$CI_TOOLKIT]
    depends_on:
      - "test"
      - "validate"
      - "lint"
    if: build.tag != null

  ###################
  # Prototype Builds of Demo Projects
  ###################
  - group: ":appcenter: Prototype Builds"
    steps:
      - label: "🛠️ Build SwiftUI Demo"
        key: build_swiftui
        depends_on: test
        plugins: [$CI_TOOLKIT]
        command: |
          install_gems
          BUILD_NUMBER=$BUILDKITE_BUILD_NUMBER make build-demo-for-distribution-swiftui
        artifact_paths:
          - ".build/artifacts/*.ipa"
          - ".build/artifacts/*.dSYM.zip"

      - label: "⬆️ Upload SwiftUI Demo to App Center"
        depends_on: build_swiftui
        plugins: [$CI_TOOLKIT]
        command: .buildkite/commands/upload-to-appcenter.sh SwiftUI
        if: build.pull_request.id != null

      - label: "🛠️ Build UIKit Demo"
        key: build_uikit
        depends_on: test
        plugins: [$CI_TOOLKIT]
        command: |
          install_gems
          BUILD_NUMBER=$BUILDKITE_BUILD_NUMBER make build-demo-for-distribution-uikit
        artifact_paths:
          - ".build/artifacts/*.ipa"
          - ".build/artifacts/*.dSYM.zip"

      - label: "⬆️ Upload UIKit Demo to App Center"
        depends_on: build_uikit
        plugins: [$CI_TOOLKIT]
        command: .buildkite/commands/upload-to-appcenter.sh UIKit
        if: build.pull_request.id != null
