# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Variables used in this pipeline are defined in `shared-pipeline-vars`, which is `source`'d before calling `buidkite-agent pipeline upload`

agents:
  queue: "mac"
env:
  IMAGE_ID: $IMAGE_ID

steps:
  #################
  # Lint Source files
  #################
  - label: "🧪 Lint"
    key: "lint"
    command: |
      echo "--- 🛠 Linting"
      make lint

  #################
  # Build and Test
  #################
  - label: "🧪 Build and Test"
    key: "test"
    command: |
      echo "--- 🛠 Building + Testing"
      make test
  
  #################
  # Build Demo
  #################
  - label: "🧪 Build Demo Project"
    key: "test_demo"
    command: |
      echo "--- :rubygems: Setting up Gems"
      make bundle-install

      echo "--- 🛠 Building Demo (Swift)"
      make build-demo-swift

      echo "--- 🛠 Building Demo (SwiftUI)"
      make build-demo-swiftui 

  ###################
  # Validate Podspec
  ###################
  - label: "🧪 Validate Podspec"
    key: "validate"
    command: |
      echo "--- :microscope: Validate Podspec"
      make validate-pod

  #################
  # Publish the Podspec (if we're building a tag)
  #################
  - label: "⬆️ Publish Podspec"
    key: "publish"
    command: |
      .buildkite/commands/publish-pod.sh "Gravatar.podspec"
      .buildkite/commands/publish-pod.sh "GravatarUI.podspec"
    plugins: [$CI_TOOLKIT]
    depends_on:
      - "test"
      - "test_demo"
      - "validate"
      - "lint"
    if: build.tag != null
    agents:
      queue: "mac"
