# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

# Variables used in this pipeline are defined in `shared-pipeline-vars`, which is `source`'d before calling `buidkite-agent pipeline upload`

agents:
  queue: "mac"
env:
  IMAGE_ID: $IMAGE_ID

steps:
  #################
  # Lint Source files
  #################
  - label: "🧪 Lint"
    key: "lint"
    command: |
      echo "--- 🛠 Linting"
      make lint

  #################
  # Build and Test
  #################
  - label: "🧪 Build and Test"
    key: "test"
    command: |
      validate_swift_package
    plugins: [$CI_TOOLKIT]

  ###################
  # Validate Podspec
  ###################
  - label: "🧪 Validate Podspecs"
    key: "validate"
    command: |
      .buildkite/commands/validate-pods.sh
    plugins: [$CI_TOOLKIT]

  #######################
  # Publish the Podspecs (if we're building a tag)
  #######################
  - label: "⬆️ Publish Podspecs"
    key: "publish"
    command: |
      .buildkite/commands/publish-pod.sh "Gravatar.podspec"
      .buildkite/commands/publish-pod.sh "GravatarUI.podspec"
    plugins: [$CI_TOOLKIT]
    depends_on:
      - "test"
      - "test_demo"
      - "validate"
      - "lint"
    if: build.tag != null

  ###################
  # Prototype Builds of Demo Projects
  ###################
  - group: ":appcenter: Prototype Builds"
    steps:
      - label: ":package: Build SwiftUI demo"
        key: build_swiftui
        depends_on: test
        command: BUILD_NUMBER=$BUILDKITE_BUILD_NUMBER make build-demo-for-distribution-swiftui
        artifact_paths:
          - ".build/artifacts/*.ipa"
          - ".build/artifacts/*.dSYM.zip"

      - label: ":arrow_up: Upload SwiftUI demo to App Center"
        depends_on: build_swiftui
        plugins: [$CI_TOOLKIT]
        command: .buildkite/commands/upload-to-appcenter.sh SwiftUI

      - label: ":package: Build UIKit demo"
        key: build_uikit
        depends_on: test
        command: BUILD_NUMBER=$BUILDKITE_BUILD_NUMBER make build-demo-for-distribution-uikit
        artifact_paths:
          - ".build/artifacts/*.ipa"
          - ".build/artifacts/*.dSYM.zip"

      - label: ":arrow_up: Upload UIKit demo to App Center"
        depends_on: build_uikit
        plugins: [$CI_TOOLKIT]
        command: .buildkite/commands/upload-to-appcenter.sh UIKit
