#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

export CI_TOOLKIT="automattic/a8c-ci-toolkit#3.2.2"

## Supported versions of Swift
# Swift 6.0
export SWIFT_6_0_IMAGE_ID="xcode-16.2-macos-14.7.1-v1"
export SWIFT_6_0_VERSION="6_0"  # Use `_` instead of `.` since these are used in labels
export SWIFT_6_0_DEVICE="default"  # Use the default value in Fastlane
export SWIFT_6_0_OS="18.0"

# Swift 5.10
export SWIFT_5_10_IMAGE_ID="xcode-15.4"
export SWIFT_5_10_VERSION="5_10"  # Use `_` instead of `.` since these are used in labels
export SWIFT_5_10_DEVICE="default"  # Use the default value in Fastlane
export SWIFT_5_10_OS="17.5"
