#!/bin/sh

# This file is `source`'d before calling `buildkite-agent pipeline upload`, and can be used
# to set up some variables that will be interpolated in the `.yml` pipeline before uploading it.

export IMAGE_ID=$(sed -n 's/version: /xcode-/p' .xcode-version)

export CI_TOOLKIT="automattic/a8c-ci-toolkit#3.0.1"
