# frozen_string_literal: true

default_platform(:ios)

OS = '17.2'
IPHONE_DEVICE = "iPhone SE (3rd generation) (#{OS})"

platform :ios do
  desc 'Builds the project and runs tests'
  lane :test do
    run_tests(
      package_path: '.',
      scheme: 'Gravatar-Package',
      device: IPHONE_DEVICE,
      prelaunch_simulator: true,
      clean: true,
      buildlog_path: File.join(__dir__, '.build', 'logs'),
      derived_data_path: File.join(__dir__, '.build', 'derived-data')
    )
  end

  lane :build_demo do |options|
    scheme = options.fetch(:scheme, 'Gravatar-Demo')

    scan(
      project: 'Demo/Gravatar-Demo.xcodeproj',
      scheme: scheme,
      configuration: 'Debug',
      device: IPHONE_DEVICE,
      clean: true,
      build_for_testing: true,
      buildlog_path: File.join(__dir__, 'build', 'logs'),
      derived_data_path: File.join(__dir__, 'build', 'derived-data'),
      disable_package_automatic_updates: true,
    )
  end
end