# Name your workflow.
name: Deploy Gravatar DocC
on:
  # Runs on pushes and PRs targeting the default branch
  push:
    branches: [ "test-docc-2" ]
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  GRAVATAR_URL: "gravatar/${{ github.ref_name }}"

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      # Must be set to this for deploying to GitHub Pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-13
    steps:
      - run: echo $GRAVATAR_URL
      - run: echo "$GRAVATAR_URL"
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Switch Xcode 🔄
        run: sudo xcode-select --switch /Applications/Xcode_15.0.app
      - name: Build DocC
        run: |
          xcodebuild docbuild -scheme Gravatar \
            -derivedDataPath /tmp/docbuild \
            -destination 'generic/platform=iOS';
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting /tmp/docbuild/Build/Products/Debug-iphoneos/Gravatar.doccarchive \
            --hosting-base-path Gravatar-SDK-iOS/$GRAVATAR_URL \
            --output-path docs;
          echo "<script>window.location.href += \"$GRAVATAR_URL/documentation/gravatar\"</script>" > docs/index.html;

      - name: Move generated docs to branch directory
        run: |
          mkdir -p ./_site/$GRAVATAR_URL && mv ./docs/* ./_site/$GRAVATAR_URL/;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload only docs directory
          path: '_site'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
